# Generated by Django 3.0 on 2020-01-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeaconAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('work_location', models.CharField(blank=True, max_length=200, null=True)),
                ('desktop', models.CharField(blank=True, max_length=200, null=True)),
                ('laptop', models.CharField(blank=True, max_length=200, null=True)),
                ('desk_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('single_monitor', models.CharField(blank=True, max_length=200, null=True)),
                ('second_monitor', models.CharField(blank=True, max_length=200, null=True)),
                ('third_monitor', models.CharField(blank=True, max_length=200, null=True)),
                ('docking_station', models.CharField(blank=True, max_length=200, null=True)),
                ('printer', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
